package com.assessment.common.util;

import javax.print.DocFlavor.STRING;

public interface AdaptiveConstants {
	
	String ADAPTIVE_ASSESSMENT_COMPLETE ="ASSESSMENT_COMPLETE";
	
	String ADAPTIVE_ASSESSMENT_NO_PREV = "ASSESSMENT_CAN_NOT_GO_BACK";

	String NUMBER_REGRESSIONS_EXCEEDED = "NO_REGRESSIONS_EXCEEDED_STOP_TEST";
	
	String NO_QUESTIONS_CURRENT_LEVEL = "NO_QUESTIONS_CURRENT_LEVEL";
	
	String REACHED_LEVEL_1 = "REACHED_LEVEL_1";
	
	String ASSESSMENT_COMPLETE_FOR_USER = "ASSESSMENT_COMPLETE_FOR_USER";
	
	String WRONG_LEVEL = "WRONG_LEVEL";
}
